// <auto-generated />
using System;
using ImageCompress.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImageCompress.API.Migrations
{
    [DbContext(typeof(ImageCompressContext))]
    [Migration("20220309172052_Image")]
    partial class Image
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImageCompress.API.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d28888e9-2ba9-473a-a40f-e38cb54f9b35"),
                            CreationDate = new DateTimeOffset(new DateTime(2022, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Format = "png",
                            Height = 1280,
                            Size = 188,
                            Titre = "Image éléphant",
                            Url = "https://www.referenseo.com/wp-content/uploads/2019/03/image-attractive.jpg",
                            Width = 720
                        },
                        new
                        {
                            Id = new Guid("6b448be7-59c1-42d5-9070-0d058e5bd66f"),
                            CreationDate = new DateTimeOffset(new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Format = "png",
                            Height = 630,
                            Size = 1980,
                            Titre = "Paysage montagne",
                            Url = "https://i.ibb.co/gT43K7r/C-est-le-titre.png",
                            Width = 1200
                        },
                        new
                        {
                            Id = new Guid("2902b665-1190-4c70-9915-b9c2d7680450"),
                            CreationDate = new DateTimeOffset(new DateTime(2019, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Format = "png",
                            Height = 647,
                            Size = 813,
                            Titre = "Nuage",
                            Url = "https://i.ibb.co/Tq1vKSx/Nuage.png",
                            Width = 1150
                        },
                        new
                        {
                            Id = new Guid("102b566b-ba1f-404c-b2df-e2cde39ade09"),
                            CreationDate = new DateTimeOffset(new DateTime(1702, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Format = "png",
                            Height = 432,
                            Size = 733,
                            Titre = "Elden Ring Media",
                            Url = "https://i.ibb.co/SwBvMN9/Elden-Ring-Media.png",
                            Width = 768
                        },
                        new
                        {
                            Id = new Guid("5b3621c0-7b12-4e80-9c8b-3398cba7ee05"),
                            CreationDate = new DateTimeOffset(new DateTime(1690, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            Format = "png",
                            Height = 1200,
                            Size = 3524,
                            Titre = "Spider Man",
                            Url = "https://i.ibb.co/tBYD8kG/Spider-Man.png",
                            Width = 1200
                        },
                        new
                        {
                            Id = new Guid("2aadd2df-7caf-45ab-9355-7f6332985a87"),
                            CreationDate = new DateTimeOffset(new DateTime(1723, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Format = "png",
                            Height = 410,
                            Size = 519,
                            Titre = "Voiture",
                            Url = "https://i.ibb.co/pxmCsCB/Voiture.png",
                            Width = 750
                        },
                        new
                        {
                            Id = new Guid("2ee49fe3-edf2-4f91-8409-3eb25ce6ca51"),
                            CreationDate = new DateTimeOffset(new DateTime(1721, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 2, 0, 0, 0)),
                            Format = "png",
                            Height = 680,
                            Size = 1906,
                            Titre = "C'est le titre",
                            Url = "https://i.ibb.co/w79kXb0/Suricates.png",
                            Width = 1200
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
